CREATE TABLE TBL_CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    NAME VARCHAR,
    ADDRESS VARCHAR,
	CREDIT_LIMIT INT
);

CREATE TABLE TBL_CONTACTS (
    FIRST_NAME BIGINT PRIMARY KEY,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
	PHONE INT,
	CUSTOMER_ID BIGINT FOREIGN KEY REFERENCES TBL_CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE TBL_EMPLOYEES (
    EMPLOYEE_ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
	EMAIL VARCHAR,
	PHONE INT,
	HIRE_DATE VARCHAR,
    JOB_TITLE VARCHAR,
);

CREATE TABLE TBL_WAREHOUSES (
    WAREHOUSE_ID BIGINT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR
);

CREATE TABLE TBL_ORDERS (
    ORDER_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT FOREIGN KEY REFERENCES TBL_CUSTOMERS(CUSTOMER_ID),
    STATUS VARCHAR,
	EMPLOYEE_ID BIGINT FOREIGN KEY REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID),
	ORDER_DATE VARCHAR
);

CREATE TABLE TBL_PRODUCT_CATEGORIES (
    CATEGORY_ID BIGINT PRIMARY KEY,
    CATEGORY_NAME VARCHAR,
);

CREATE TABLE TBL_PRODUCTS (
    PRODUCT_ID BIGINT PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    DESCRIPTION VARCHAR,
	STANDARD_COST DECIMAL(5,2),
	LIST_PRICE DECIMAL(5,2),
	CATEGORY_ID BIGINT FOREIGN KEY REFERENCES TBL_PRODUCT_CATEGORIES(CATEGORY_ID)
);

CREATE TABLE TBL_INVENTORIES (
    PRODUCT_ID BIGINT FOREIGN KEY REFERENCES TBL_PRODUCTS(PRODUCT_ID),
    WAREHOUSE_ID BIGINT FOREIGN KEY REFERENCES TBL_WAREHOUSES(WAREHOUSE_ID),
    QUANTITY INT,
);

CREATE TABLE TBL_ITEMS (
    ITEM_ID BIGINT PRIMARY KEY,
    ORDER_ID BIGINT FOREIGN KEY REFERENCES TBL_ORDERS(ORDER_ID),
    PRODUCT_ID BIGINT FOREIGN KEY REFERENCES TBL_PRODUCTS(PRODUCT_ID),
	QUANTITY INT,
	PRICE DECIMAL(5,2)
);